config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.delete
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <div class="card">
    <%= simple_form_for(@flat) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guest %>
      <%= f.submit %>
      <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All Our Flats</h1>
  <p>All <%= @flats.count %> Flats</p>
</div>

<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4 mb-4">
        <div class="card" style="width: 18rem;">
          <img src="https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80" class="card-img-top" alt="...">
          <div class="card-body ps-4">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <i class="fa-solid fa-user"></i>
            <span class="me-3"><%= flat.number_of_guest %></span>
            <i class="fa-regular fa-euro-sign "></i>
            <span><%= flat.price_per_night %></span>
          </div>
          <div class="card-header p-4">
            <%= link_to "More info", flat_path(flat), class:'class="btn btn-primary btn-sm text-decoration-none '%>
            <%= link_to "Edit", edit_flat_path(flat), class:'class="btn btn-warning btn-sm text-decoration-none ' %>
            <%= link_to "Remove", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} , class:'class="btn btn-danger btn-sm text-decoration-none'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="card shadow-md p-4">
    <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guest %>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="card p-4">
    <h1><%= @flat.name %></h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar bg-body-tertiary shadow-sm py-3 mb-4">
      <div class="container">
         <%= link_to 'Simple Airbnb', flats_path, class:"navbar-brand text-info display-4" %>
         <%= link_to "NEW FLAT", new_flat_path, class:'btn btn-primary' %>

      </div>
    </nav>
    <%= yield %>
  </body>
</html>